version: '3'
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgres/data
    restart: always
    ports:
      - '5432:5432'
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
